minVersion: '0.13.2'
github:
  owner: BYK
  repo: superset
changelogPolicy: auto
requireNames:
  - /^superset.*\.tgz$/
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: npm
  - name: github
