env:
    node: true
    es6: true
plugins:
    - markdown
rules:
    strict:
        - 2
        - global
    eqeqeq:
        - 2
        - allow-null
    block-scoped-var: 2
    wrap-iife:
        - 2
        - any
    valid-typeof: 2
    no-undef:
        - 2
        - typeof: true
    no-unused-vars:
        - 2
        - args: all
          argsIgnorePattern: "^_.+"
    no-eq-null: 2
    no-bitwise: 2
    no-use-before-define: 1
    no-empty: 2
    no-new: 2
    no-throw-literal: 2
    no-loop-func: 2
    no-inner-declarations: 2
    no-array-constructor: 2
    no-cond-assign: 2
    no-console: 2
    no-control-regex: 2
    no-dupe-args: 2
    no-duplicate-case: 2
    no-empty-character-class: 2
    no-invalid-regexp: 2
    no-mixed-spaces-and-tabs: 2
    no-regex-spaces: 2
    no-magic-numbers: 1

    require-jsdoc: 2
    valid-jsdoc: 2

    # Style
    indent: 2
    linebreak-style: 2
    semi: 2
    semi-spacing: 2
    block-spacing: 2
    id-length:
        - 2
        - exceptions: ["$", "_", "i", "j"]
    no-irregular-whitespace: 2
    no-trailing-spaces: 2
    no-spaced-func: 2
    max-len: [1, 120, 4]
    quotes:
        - 2
        - double

    space-before-keywords: 2
    space-after-keywords: 2
    space-return-throw-case: 2
    space-before-blocks: 2
    space-before-function-paren:
        - 2
        - anonymous: always
          named: never
    space-infix-ops: 2
    space-unary-ops: 2
    spaced-comment:
        - 2
        - always
        - exceptions: ["-", "=", "/"]
          markers: [","]
    new-cap: 2
    new-parens: 2
    no-undef-init: 2
    no-extend-native: 2
    no-caller: 2
    no-native-reassign: 2
    consistent-this:
        - 1
        - _this

    comma-dangle:
        - 2
        - "always-multiline"
    camelcase:
        - 2
        - properties: never
    curly:
        - 2
        - multi-or-nest
        - consistent
    object-curly-spacing:
        - 2
        - always
    key-spacing: 2
    no-multi-spaces:
        - 2
        - exceptions:
            Property: false
    no-shadow: 1
    no-shadow-restricted-names: 2
    dot-notation: 2
    operator-assignment: 2
    no-implicit-coercion: 2
    no-constant-condition: 2
    no-debugger: 2
    no-dupe-keys: 2
    no-extra-boolean-cast: 2
    no-extra-semi: 2
    no-ex-assign: 2
    no-func-assign: 2
    no-negated-in-lhs: 2
    no-negated-condition: 2
    no-obj-calls: 2
    no-sparse-arrays: 2
    no-unreachable: 2
    no-else-return: 2
    no-useless-call: 2
    no-useless-concat: 2
    use-isnan: 2
    default-case: 1
    guard-for-in: 1
    no-alert: 1
    no-empty-label: 2
    no-eval: 2
    no-fallthrough: 2
    no-implied-eval: 2
    no-labels: 2
    no-label-var: 2
    no-iterator: 2
    no-lone-blocks: 2
    no-multi-str: 2
    no-new-func: 2
    no-new-object: 2
    no-new-wrappers: 2
    no-octal: 2
    no-octal-escape: 2
    no-proto: 2
    no-redeclare: 2
    no-return-assign: 1
    no-self-compare: 2
    no-script-url: 2
    no-sequences: 2
    no-unused-expressions: 2
    no-with: 2
    radix: 2
    no-catch-shadow: 2
    no-delete-var: 2
    comma-spacing: 2
    comma-style: 2
    no-unneeded-ternary: 2
    no-nested-ternary: 2
    no-lonely-if: 2
    no-extra-bind: 2
    no-extra-parens: 2
    dot-location:
        - 2
        - property
    one-var:
        - 2
        - uninitialized: always
          initialized: never
    global-require: 2
    # ES2015
    arrow-parens:
        - 2
        - as-needed
    arrow-body-style:
        - 2
        - as-needed
    arrow-spacing: 2
    no-arrow-condition: 2
    generator-star-spacing:
        - 2
        - after
    no-class-assign: 2
    no-dupe-class-members: 2

    object-shorthand: 2
    prefer-arrow-callback: 2
    prefer-const: 2
    prefer-template: 2
    require-yield: 2
