import stylistic from "@stylistic/eslint-plugin";
import globals from "globals";

export default [
  {
    ignores: ["coverage/**", "node_modules/**"],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    plugins: {
      "@stylistic": stylistic,
    },
    rules: {
      // Core rules
      "strict": "error",
      "eqeqeq": ["error", "allow-null"],
      "block-scoped-var": "error",
      "wrap-iife": ["error", "any"],
      "valid-typeof": "error",
      "no-undef": ["error", { typeof: true }],
      "no-unused-vars": ["error", { args: "all", argsIgnorePattern: "^_.+" }],
      "no-implicit-globals": "error",
      "no-self-assign": "error",
      "no-eq-null": "error",
      "no-bitwise": "error",
      "no-use-before-define": "warn",
      "no-empty": "error",
      "no-empty-function": "error",
      "no-new": "error",
      "no-throw-literal": "error",
      "no-loop-func": "error",
      "no-unmodified-loop-condition": "warn",
      "no-inner-declarations": "error",
      "no-array-constructor": "error",
      "no-cond-assign": "error",
      "no-console": "error",
      "no-control-regex": "error",
      "no-dupe-args": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-invalid-regexp": "error",
      "no-regex-spaces": "error",
      "array-callback-return": "error",
      "no-useless-constructor": "error",
      "no-var": "error",
      "no-magic-numbers": "warn",

      // Identifier rules
      "id-length": ["error", { exceptions: ["$", "_", "i", "j"] }],
      "no-irregular-whitespace": "error",
      "new-cap": "error",
      "new-parens": "error",
      "no-undef-init": "error",
      "no-extend-native": "error",
      "no-caller": "error",
      "no-global-assign": "error", // was no-native-reassign
      "consistent-this": ["warn", "_this"],

      // Object/property rules
      "camelcase": ["error", { properties: "never" }],
      "curly": ["error", "multi-or-nest", "consistent"],
      "no-shadow": "warn",
      "no-shadow-restricted-names": "error",
      "dot-notation": "error",
      "operator-assignment": "error",
      "no-implicit-coercion": "error",
      "no-constant-condition": "error",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-extra-boolean-cast": "error",
      "no-ex-assign": "error",
      "no-func-assign": "error",
      "no-unsafe-negation": "error", // was no-negated-in-lhs
      "no-negated-condition": "error",
      "no-obj-calls": "error",
      "no-sparse-arrays": "error",
      "no-unreachable": "error",
      "no-else-return": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "use-isnan": "error",
      "default-case": "warn",
      "guard-for-in": "warn",
      "no-alert": "warn",
      "no-eval": "error",
      "no-fallthrough": "error",
      "no-case-declarations": "error",
      "no-implied-eval": "error",
      "no-labels": ["error", { allowSwitch: true }],
      "no-label-var": "error",
      "no-iterator": "error",
      "no-lone-blocks": "error",
      "no-multi-str": "error",
      "no-new-func": "error",
      "no-object-constructor": "error", // was no-new-object
      "no-new-wrappers": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-return-assign": "warn",
      "no-self-compare": "error",
      "no-script-url": "error",
      "no-sequences": "error",
      "no-unused-expressions": "error",
      "no-with": "error",
      "radix": "error",
      "no-delete-var": "error",
      "no-unneeded-ternary": "error",
      "no-nested-ternary": "error",
      "no-lonely-if": "error",
      "no-extra-bind": "error",
      "one-var": ["error", { uninitialized: "always", initialized: "never" }],
      "no-confusing-arrow": "error",
      "no-class-assign": "error",
      "no-dupe-class-members": "error",
      "object-shorthand": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-template": "error",
      "require-yield": "error",
      "arrow-body-style": ["error", "as-needed"],

      // Stylistic rules (via @stylistic plugin)
      "@stylistic/indent": "error",
      "@stylistic/linebreak-style": "error",
      "@stylistic/semi": "error",
      "@stylistic/semi-spacing": "error",
      "@stylistic/block-spacing": "error",
      "@stylistic/no-whitespace-before-property": "error",
      "@stylistic/template-curly-spacing": "error",
      "@stylistic/no-trailing-spaces": "error",
      "@stylistic/function-call-spacing": "error", // was no-spaced-func
      "@stylistic/max-len": ["warn", 120, 4],
      "@stylistic/quotes": ["error", "double"],
      "@stylistic/keyword-spacing": "error",
      "@stylistic/space-before-blocks": "error",
      "@stylistic/space-before-function-paren": [
        "error",
        { anonymous: "always", named: "never" },
      ],
      "@stylistic/space-infix-ops": "error",
      "@stylistic/space-unary-ops": "error",
      "@stylistic/spaced-comment": [
        "error",
        "always",
        { exceptions: ["-", "=", "/"], markers: [","] },
      ],
      "@stylistic/comma-dangle": ["error", "always-multiline"],
      "@stylistic/object-curly-spacing": ["error", "always"],
      "@stylistic/key-spacing": "error",
      "@stylistic/no-multi-spaces": ["error", { exceptions: { Property: false } }],
      "@stylistic/no-extra-semi": "error",
      "@stylistic/no-extra-parens": "error",
      "@stylistic/dot-location": ["error", "property"],
      "@stylistic/arrow-parens": ["error", "as-needed"],
      "@stylistic/arrow-spacing": "error",
      "@stylistic/generator-star-spacing": ["error", "after"],
      "@stylistic/yield-star-spacing": "error",
      "@stylistic/comma-spacing": "error",
      "@stylistic/comma-style": "error",
      "@stylistic/no-mixed-spaces-and-tabs": "error",
    },
  },
  {
    files: ["test/**/*.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        beforeEach: "readonly",
      },
    },
    rules: {
      "no-magic-numbers": "off",
      "no-unused-expressions": "off",
      "no-new": "off",
      "prefer-arrow-callback": "off",
      "@stylistic/max-len": "off",
    },
  },
];
