name: Build
on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  job_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20', '22']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test

  job_coverage:
    name: Coverage Upload
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test with coverage
        run: pnpm test:ci
      - name: Upload coverage to Codecov
        uses: getsentry/codecov-action@main
        with:
          files: ./coverage/lcov.info

  job_artifacts:
    name: Artifacts Upload
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: NPM Pack
        run: npm pack
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: ${{ github.workspace }}/*.tgz
